/* CERT Field Guide service worker. Generated by build/build_app.py; do not edit sw.js by hand. */
'use strict';
const VERSION = '9b560e31c80e';
const CACHE = 'cert-fg-' + VERSION;
const PRECACHE = [
 "./",
 "css/app.css",
 "data/content.json",
 "data/local-protocols.json",
 "icons/apple-touch-icon.png",
 "icons/favicon-32.png",
 "icons/icon-192.png",
 "icons/icon-512.png",
 "icons/icon-maskable-512.png",
 "icons/lockup-dark.svg",
 "icons/lockup-light.svg",
 "index.html",
 "js/app.js",
 "manifest.webmanifest"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' bypasses the HTTP cache so we never pin a stale file
    await cache.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })));
    // first install: activate immediately; later updates wait until the user taps "Update"
    if (!(await hasOldCache())) self.skipWaiting();
  })());
});

async function hasOldCache() {
  const keys = await caches.keys();
  return keys.some((k) => k.startsWith('cert-fg-') && k !== CACHE);
}

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('cert-fg-') && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
  if (event.data === 'VERSION' && event.source) event.source.postMessage({ version: VERSION });
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;   // the app never fetches cross-origin
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (req.mode === 'navigate') {
      // hash-routed single page: always serve the cached shell
      return (await cache.match('./index.html')) || (await cache.match('./')) || fetch(req);
    }
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try { return await fetch(req); }
    catch (e) { return new Response('Offline and not cached', { status: 503, headers: { 'Content-Type': 'text/plain' } }); }
  })());
});
